# Generated by Django 2.2.12 on 2020-04-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200409_2043'),
        ('users', '0002_auto_20200409_2127'),
    ]

    operations = [
    ]
